mount-dir: "./database/dbs/games/tertiary/mount"
data-dir: "./database/dbs/games/tertiary/data"

http:
  addr: ":20204"

static:
  primary: false
  hostname: "tuffix-vm"
  advertise-url: "http://tuffix-vm:20202"